# 主题：hexo-theme-webstack(https://github.com/HCLonely/hexo-theme-webstack)
favicon: /images/favicon.png
# [可选]分享网站到 twitter 和 facebook 时的图片。
# /images/girl.png  
banner: 

logo:
  expanded: /images/logo@2x.png
  collapsed: /images/logo-collapsed@2x.png
  dark: /images/logo_dark@2x.png

flag:
  - name: Chinese
    default: true
    icon: flag-cn
    index: /index.html

search: true

userDefinedSearchData:
  custom: false
  thisSearch: https://www.baidu.com/s?wd=
  thisSearchIcon: url(/images/baidu_favicon.ico)
  hotStatus: true
  data:
    - name: 百度
      img: url(/images/baidu_favicon.ico)
      url: https://www.baidu.com/s?wd=

expandAll: false
menu:
  - name: 常用推荐
    icon: fa fa-star
    config: favorite
  - name: 博客论坛
    icon: fa fa-blog
    config: blogBBS
  - name: 在线工具
    icon: fa fa-bolt
    config: onlineTools
  - name: 学习教育
    icon: fa fa-book
    config: studyTutorial
  - name: 常用工具
    icon: fa fa-briefcase
    submenu:
      - name: 代码托管
        icon: fa fa-code
        config: codeManaged
      - name: 实用软件
        icon: fa fa-wrench
        config: commonTools
      - name: 浏览器插件
        icon: fa fa-puzzle-piece
        config: plugIn
  - name: 博客收藏
    icon: fa fa-bookmark
    config: favoriteBlog
  - name: 产品设计
    icon: fa fa-palette
    config: productDesign
  - name: 新闻资讯
    icon: fa fa-newspaper
    config: news
  - name: 休闲娱乐
    icon: fa fa-headphones
    config: recreation

  # - name: 模板
  #   url: xxx
  #   img: /images/logos/default.png
  #   description: 简介

about:
  url: /about/
  icon: fa fa-user
  name: 关于本站

aboutPage:
  website:
    head: 关于本站
    html: '<blockquote><p>本站是<a href="https://chris-z-su.github.io/">Bookpackage</a>的导航网站。</p></blockquote>'
  webmaster:
    head: 关于站长
    name: Chris
    url: https://chris-z-su.github.io/NavigationPage/
    img: /images/avatar.jpg
    description: 为实现中华民族伟大复兴的中国梦而努力奋斗。
    html: '<br /><span>这个人很懒，什么都没留下。</span>'

since: 2022

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: 总访问量$pv
  uv: 总访客数$uv

custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
  body: |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
