# 主题：hexo-theme-webstack(https://github.com/HCLonely/hexo-theme-webstack)
favicon: /images/favicon.png
# [可选]分享网站到 twitter 和 facebook 时的图片。
# /images/girl.png  
banner: 

logo:
  expanded: /images/logo@2x.png
  collapsed: /images/logo-collapsed@2x.png
  dark: /images/logo_dark@2x.png

flag:
  - name: Chinese
    default: true
    icon: flag-cn
    index: /index.html

search: true

userDefinedSearchData:
  custom: true
  thisSearch: https://cn.bing.com/search?q=
  thisSearchIcon: url(./images/search_icon.png) 0px -40px
  hotStatus: true
  data:
    - name: 百度
      img: url(./images/search_icon.png) -80px 0px
      position: 0px 0px
      url: https://www.baidu.com/s?wd=
    - name: 必应
      img: url(./images/search_icon.png) -80px -25px
      position: 0px -40px
      url: https://cn.bing.com/search?q=
    - name: 谷歌
      img: url(./images/search_icon.png) -105px 0px
      position: -40px 0px
      url: https://www.google.com/search?q=
    - name: GitHub
      img: url(./images/search_icon.png) -80px -175px
      position: 0px -280px
      url: https://github.com/search?utf8=✓&q=
    - name: Stack Overflow
      img: url(./images/search_icon.png) -105px -75px
      position: -40px -120px
      url: https://stackoverflow.com/nocaptcha?s=
    - name: 开发者搜索
      img: url(./images/search_icon.png) -105px -50px
      position: -40px -80px
      url: https://kaifa.baidu.com/searchPage?wd=
    - name: Yandex
      img: url(./images/search_icon.png) -80px -100px
      position: 0px -160px
      url: https://yandex.com/search/?text=
    - name: 360搜索
      img: url(./images/search_icon.png) -105px -25px
      position: -40px -40px
      url: https://www.so.com/s?q=
    # - name: Phind
    #   img: url(./images/search_icon.png) -105px -25px
    #   position: -40px -40px
    #   url: https://www.phind.com/search?source=searchbox&q=
    - name: 搜狗
      img: url(./images/search_icon.png) -80px -50px
      position: 0px -80px
      url: https://www.sogou.com/web?query=
    - name: Minecraft Wiki
      img: url(./images/search_icon.png) -80px -75px
      position: 0px -120px
      url: https://minecraft.fandom.com/zh/wiki/Special:Search?query=
    - name: 知乎
      img: url(./images/search_icon.png) -105px -100px
      position: -40px -160px
      url: https://www.zhihu.com/search?type=content&q=
    - name: 微博
      img: url(./images/search_icon.png) -80px -125px
      position: 0px -200px
      url: https://s.weibo.com/weibo/
    - name: B站
      img: url(./images/search_icon.png) -105px -125px
      position: -40px -200px
      url: http://search.bilibili.com/all?keyword=
    - name: 豆瓣
      img: url(./images/search_icon.png) -80px -150px
      position: 0px -240px
      url: https://www.douban.com/search?source=suggest&q=
    - name: 优酷
      img: url(./images/search_icon.png) -105px -150px
      position: -40px -240px
      url: https://so.youku.com/search_video/q_

expandAll: false
menu:
  - name: 常用推荐
    icon: fa fa-star
    config: favorite
  - name: 博客论坛
    icon: fa fa-blog
    config: blogBBS
  - name: 在线工具
    icon: fa fa-bolt
    config: onlineTools
  - name: 学习教育
    icon: fa fa-book
    config: studyTutorial
  - name: 常用工具
    icon: fa fa-briefcase
    submenu:
      - name: 代码托管
        icon: fa fa-code
        config: codeManaged
      - name: 实用软件
        icon: fa fa-wrench
        config: commonTools
      - name: 浏览器插件
        icon: fa fa-puzzle-piece
        config: plugIn
  - name: 博客收藏
    icon: fa fa-bookmark
    config: favoriteBlog
  - name: 产品设计
    icon: fa fa-palette
    config: productDesign
  - name: 新闻资讯
    icon: fa fa-newspaper
    config: news
  - name: 休闲娱乐
    icon: fa fa-headphones
    config: recreation

  # - name: 模板
  #   url: xxx
  #   img: /images/logos/default.png
  #   description: 简介

about:
  url: /about/
  icon: fa fa-user
  name: 关于本站

aboutPage:
  website:
    head: 关于本站
    html: '<blockquote><p>本站是<a href="https://chris-z-su.github.io/">Bookpackage</a>的导航网站。</p></blockquote>'
  webmaster:
    head: 关于站长
    name: Chris
    url: https://chris-z-su.github.io/NavigationPage/
    img: /images/avatar.jpg
    description: 为实现中华民族伟大复兴的中国梦而努力奋斗。
    html: '<br /><span>这个人很懒，什么都没留下。</span>'

since: 2022

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: 总访问量$pv
  uv: 总访客数$uv

custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
  body: |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
