# 产品设计
- name: Icons | Font Awesome
  url: https://fontawesome.com/icons
  img: /images/logos/fontawesome.png
  description: Used by millions of designers, devs, & content creators. Open-source. Always free. Check out the new Thin style, now available in Font Awesome 6.
- name: 花瓣网 - 陪你做生活的设计师（创意灵感天堂，搜索、发现设计灵感、设计素材）
  url: https://huaban.com/
  img: https://st0.dancf.com/static/02/202201151128-a455.svg
  description: 花瓣网, 设计师寻找灵感的天堂！图片素材领导者，帮你采集、发现网络上你喜欢的事物。你可以用它收集灵感,保存有用的素材,计划旅行,晒晒自己想要的东西


