# 产品设计
- name: Icons | Font Awesome
  url: https://fontawesome.com/icons
  img: /images/logos/fontawesome.png
  description: Used by millions of designers, devs, & content creators. Open-source. Always free. Check out the new Thin style, now available in Font Awesome 6.
- name: 花瓣网 - 陪你做生活的设计师（创意灵感天堂,搜索、发现设计灵感、设计素材）
  url: https://huaban.com/
  img: /images/logos/huaban.svg
  description: 花瓣网, 设计师寻找灵感的天堂！图片素材领导者,帮你采集、发现网络上你喜欢的事物。你可以用它收集灵感,保存有用的素材,计划旅行,晒晒自己想要的东西
- name: 美叶- 优质灵感辑录
  url: https://www.meiye.art/
  img: /images/logos/meiye.ico
  description: 美叶,为设计师,创意人提供有价值的设计参考。灵感采集,优质素材获取,时刻Follow最新流行设计趋势
- name: 演示星球
  url: https://www.pop-ppt.com/
  img: /images/logos/pop-ppt.svg
  description: 免费PPT模板下载
- name: PPT超级市场官网-PPT模板免费下载、最新PPT成品搜索
  url: https://www.pptsupermarket.com/
  img: /images/logos/pptsupermarket.ico
  description: 免费下载PPT模板与PPT作品，提供免费的PPT代做服务，提供一站式PPT(模板、定制、工具、教程)服务，有了它，一切制作PPT的烦恼都将成为过去！
- name: 字由-让设计更有价值
  url: https://www.hellofont.cn/
  img: /images/logos/hellofont.png
  description: 字由是为设计师量身定做的一款字体下载管理工具。
- name: 花火数图
  url: https://hanabi.cn/h2/index
  img: /images/logos/hanabi.ico
  description: 花火hanabi是免费的在线图表制作工具。
- name: Beautiful Free Images & Pictures | Unsplash
  url: https://unsplash.com/
  img: /images/logos/unsplash.svg
  description: Beautiful, free images and photos that you can download and use for any project. Better than any royalty free or stock photos.
- name: Haikei
  url: https://app.haikei.app/
  img: /images/logos/haikei.png
  description: A web-based design tool to generate unique SVG design assets for websites, social media, blog posts, desktop and mobile wallpapers, posters, and more! Our generators let you discover, customize, randomize, and export generative SVG design assets ready to use with your favorite design tools.
- name: 免费的图标、剪贴画插图、照片和音乐
  url: https://igoutu.cn/
  img: /images/logos/igoutu.png
  description: 免费下载设计素材：图标、照片、矢量插图和视频音乐。所有素材均由设计师制作 → 质量始终如一⚡️
- name: Picular
  url: https://picular.co/
  img: /images/logos/picular.png
  description: Picular is a rocket fast primary color generator using Google’s image search. If you ever needed the perfect yellow hex code from a banana, this is the tool for you.
